package com.gcs.db.businessDao;
// Generated Mar 17, 2018 12:55:27 PM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.GeneratedValue;

/**
 * CampaignQuestions generated by hbm2java
 */
public class CampaignQuestions implements java.io.Serializable {

	@GeneratedValue
	private int id;
	private Campaign campaign;
	private String question;
	private String option1;
	private String option2;
	private String option3;
	private String option4;
	private String prefix;
	private boolean remarks;


	public CampaignQuestions() {
	}

	public CampaignQuestions(Campaign campaign) {
		this.campaign = campaign;
	}

	public CampaignQuestions(Campaign campaign, String question, String option1, String option2, String option3,
			String option4, String prefix) {
		this.campaign = campaign;
		this.question = question;
		this.option1 = option1;
		this.option2 = option2;
		this.option3 = option3;
		this.option4 = option4;
		this.prefix = prefix;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Campaign getCampaign() {
		return this.campaign;
	}

	public void setCampaign(Campaign campaign) {
		this.campaign = campaign;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public String getOption1() {
		return this.option1;
	}

	public void setOption1(String option1) {
		this.option1 = option1;
	}

	public String getOption2() {
		return this.option2;
	}

	public void setOption2(String option2) {
		this.option2 = option2;
	}

	public String getOption3() {
		return this.option3;
	}

	public void setOption3(String option3) {
		this.option3 = option3;
	}

	public String getOption4() {
		return this.option4;
	}

	public void setOption4(String option4) {
		this.option4 = option4;
	}

	public String getPrefix() {
		return this.prefix;
	}

	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

	public boolean isRemarks() {
		return remarks;
	}

	public void setRemarks(boolean remarks) {
		this.remarks = remarks;
	}

	@Override
	public String toString() {
		return "CampaignQuestions [id=" + id + ", campaign=" + campaign + ", question=" + question + ", option1="
				+ option1 + ", option2=" + option2 + ", option3=" + option3 + ", option4=" + option4 + ", prefix="
				+ prefix + "]";
	}

}
