package com.gcs.db.businessDao;
// Generated Mar 17, 2018 12:55:27 PM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.GeneratedValue;

/**
 * Campaign generated by hbm2java
 */
public class Campaign implements java.io.Serializable {

	@GeneratedValue
	private int id;
	private VendorType vendorType;
	private String name;
	public Campaign() {
	}

	public Campaign(VendorType vendorType) {
		this.vendorType = vendorType;
	}

	public Campaign(VendorType vendorType, String name) {
		this.vendorType = vendorType;
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VendorType getVendorType() {
		return this.vendorType;
	}

	public void setVendorType(VendorType vendorType) {
		this.vendorType = vendorType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Override
	public String toString() {
		return "Campaign [id=" + id + ", vendorType=" + vendorType + ", name=" + name + "]";
	}


}
